import tomllib
from pathlib import Path
from typing import TypedDict


class Project(TypedDict):
    name: str
    version: str


def get_project(project: Path) -> Project:
    toml = project / "pyproject.toml"
    if not toml.exists():
        raise FileNotFoundError(f"Could not find {toml}")
    data = tomllib.loads(toml.read_text(encoding="utf-8"))
    return Project(data["project"])


def generate_project_version(path: Path):
    project = get_project(path)
    version_path = path / "src" / project["name"] / "version.py"
    version_path.write_text(f"""\
# Do not edit this file, it is automatically generated by scripts/py-generate_version.py
VERSION = "{project['version']}"
""")


def main():
    for package in Path("packages-py").glob("*"):
        generate_project_version(package)


if __name__ == "__main__":
    main()
